import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { useEffect } from "react";


// in any layout or root component
// useEffect(() => {
//   const ping = setInterval(() => {
//       fetch(`${process.env.NEXT_PUBLIC_API_URL}/health`).catch(() => {})
//   }, 10 * 60 * 1000) // ping every 10 minutes
//   return () => clearInterval(ping)
// }, [])

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
